// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    double more = 0;
		double less = 0;
		int repTimes = Integer.parseInt(args[0]);

		for(int i=0; i<repTimes; i++)
		{
			double num = Math.random();
			if(num > 0.5)
			{
				more++;
			}
			else
			{
				less++;
			}
		}
		double ratio = more/less;
		//System.out.println("more: " + more + ", less: " + less);
		System.out.println("Ratio: " + ratio);
	}
}
